name: main
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build-and-test:
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
          - '18'
    runs-on: ubuntu-latest
    name: Tests on Node.js v${{ matrix.node }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Build sources
        run: npm run build

      - name: Run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run lint
        run: npm run lint
